# To install:
#     conda env create -f conda.yml -n <some name>

channels:
  - conda-forge
  - defaults
dependencies:
     - python=3.8
     - cftime<=1.2.1
     - ipython
     - jupyter
     - matplotlib>=3.3.3
     - nbsphinx
     - nc-time-axis<=1.2.0
     - netcdf4
     - numpy
     - pandas
     - pip
     - pip:
       - git+https://github.com/jkrasting/cmip_basins.git
       - git+https://github.com/raphaeldussin/xoverturning
     - regionmask
     - scipy
     - sphinx
     - sphinx_rtd_theme
     - xarray
     - xesmf=0.4.0
     - xgcm
